server:
  image: ivan97/ngrok
  ports:
    - "8082:80"
    - "4432:443"
    - "4443:4443"
  volumes:
    - /root/docker/volume/ngrok:/myfiles
  environment:
    - DOMAIN="tunnel.ioooo.tech"
  command: /bin/sh /server.sh
