server:
  image: ivan97/ngrok
  ports:
    - "80:80"
    - "443:443"
    - "4443:4443"
  volumes:
    - /root/docker/volume/ngromZ:/myfiles
  environment:
    - DOMAIN="tunnel.ioooo.tech"
  command: /bin/sh /server.sh
