server:
  image: ivan97/ngrok
  ports:
    - "80:80"
    - "443:443"
    - "4443:4443"
  volumes:
    - /root/docker/volume/ngrok:/myfiles
  environment:
    - DOMAIN="tunnel.iooo.tech"
  command: /bin/sh /server.sh
