server:
  image: hteen/ngrok
  ports:
    - "80:80"
    - "443:443"
    - "4443:4443"
  volumes:
    - /root/docker/volume/ngrok:/myfiles
  environment:
    - DOMAIN="tunnel.yangki.net"
  command: /bin/sh /server.sh
